sudo: required
services:
  - docker

before_install:
  - docker build -t jasonl24/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jasonl24/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"  # region comes from the aws url
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-390905103596"
  bucket_path: "docket-react"
  on:
    branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY